// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System;

using Microsoft.SqlServer.TransactSql.ScriptDom;

namespace Microsoft.CodeAnalysis.Sql.Sdk
{
    public class AllNodesVisitor : TSqlConcreteFragmentVisitor
    {
        Action<TSqlFragment> action;

        public AllNodesVisitor(Action<TSqlFragment> action)
        {
            this.action = action;
        }

        public override void Visit(CreateEventSessionStatement node) { this.action(node); }
        public override void Visit(EventDeclaration node) { this.action(node); }
        public override void Visit(EventDeclarationSetParameter node) { this.action(node); }
        public override void Visit(SourceDeclaration node) { this.action(node); }
        public override void Visit(EventDeclarationCompareFunctionParameter node) { this.action(node); }
        public override void Visit(TargetDeclaration node) { this.action(node); }
        public override void Visit(EventRetentionSessionOption node) { this.action(node); }
        public override void Visit(MemoryPartitionSessionOption node) { this.action(node); }
        public override void Visit(LiteralSessionOption node) { this.action(node); }
        public override void Visit(MaxDispatchLatencySessionOption node) { this.action(node); }
        public override void Visit(OnOffSessionOption node) { this.action(node); }
        public override void Visit(AlterEventSessionStatement node) { this.action(node); }
        public override void Visit(DropEventSessionStatement node) { this.action(node); }
        public override void Visit(AlterResourceGovernorStatement node) { this.action(node); }
        public override void Visit(CreateSpatialIndexStatement node) { this.action(node); }
        public override void Visit(SpatialIndexRegularOption node) { this.action(node); }
        public override void Visit(BoundingBoxSpatialIndexOption node) { this.action(node); }
        public override void Visit(BoundingBoxParameter node) { this.action(node); }
        public override void Visit(GridsSpatialIndexOption node) { this.action(node); }
        public override void Visit(GridParameter node) { this.action(node); }
        public override void Visit(CellsPerObjectSpatialIndexOption node) { this.action(node); }
        public override void Visit(AlterServerConfigurationStatement node) { this.action(node); }
        public override void Visit(ProcessAffinityRange node) { this.action(node); }
        public override void Visit(AlterServerConfigurationSetBufferPoolExtensionStatement node) { this.action(node); }
        public override void Visit(AlterServerConfigurationBufferPoolExtensionOption node) { this.action(node); }
        public override void Visit(AlterServerConfigurationBufferPoolExtensionContainerOption node) { this.action(node); }
        public override void Visit(AlterServerConfigurationBufferPoolExtensionSizeOption node) { this.action(node); }
        public override void Visit(AlterServerConfigurationSetDiagnosticsLogStatement node) { this.action(node); }
        public override void Visit(AlterServerConfigurationDiagnosticsLogOption node) { this.action(node); }
        public override void Visit(AlterServerConfigurationDiagnosticsLogMaxSizeOption node) { this.action(node); }
        public override void Visit(AlterServerConfigurationSetFailoverClusterPropertyStatement node) { this.action(node); }
        public override void Visit(AlterServerConfigurationFailoverClusterPropertyOption node) { this.action(node); }
        public override void Visit(AlterServerConfigurationSetHadrClusterStatement node) { this.action(node); }
        public override void Visit(AlterServerConfigurationHadrClusterOption node) { this.action(node); }
        public override void Visit(CreateAvailabilityGroupStatement node) { this.action(node); }
        public override void Visit(AlterAvailabilityGroupStatement node) { this.action(node); }
        public override void Visit(AvailabilityReplica node) { this.action(node); }
        public override void Visit(LiteralReplicaOption node) { this.action(node); }
        public override void Visit(AvailabilityModeReplicaOption node) { this.action(node); }
        public override void Visit(FailoverModeReplicaOption node) { this.action(node); }
        public override void Visit(PrimaryRoleReplicaOption node) { this.action(node); }
        public override void Visit(SecondaryRoleReplicaOption node) { this.action(node); }
        public override void Visit(LiteralAvailabilityGroupOption node) { this.action(node); }
        public override void Visit(AlterAvailabilityGroupAction node) { this.action(node); }
        public override void Visit(AlterAvailabilityGroupFailoverAction node) { this.action(node); }
        public override void Visit(AlterAvailabilityGroupFailoverOption node) { this.action(node); }
        public override void Visit(DropAvailabilityGroupStatement node) { this.action(node); }
        public override void Visit(CreateFederationStatement node) { this.action(node); }
        public override void Visit(AlterFederationStatement node) { this.action(node); }
        public override void Visit(DropFederationStatement node) { this.action(node); }
        public override void Visit(UseFederationStatement node) { this.action(node); }
        public override void Visit(DiskStatement node) { this.action(node); }
        public override void Visit(DiskStatementOption node) { this.action(node); }
        public override void Visit(CreateColumnStoreIndexStatement node) { this.action(node); }
        public override void Visit(WindowFrameClause node) { this.action(node); }
        public override void Visit(WindowDelimiter node) { this.action(node); }
        public override void Visit(WithinGroupClause node) { this.action(node); }
        public override void Visit(SelectiveXmlIndexPromotedPath node) { this.action(node); }
        public override void Visit(MergeActionClause node) { this.action(node); }
        public override void Visit(UpdateMergeAction node) { this.action(node); }
        public override void Visit(DeleteMergeAction node) { this.action(node); }
        public override void Visit(InsertMergeAction node) { this.action(node); }
        public override void Visit(CreateTypeTableStatement node) { this.action(node); }
        public override void Visit(AuditSpecificationPart node) { this.action(node); }
        public override void Visit(AuditActionSpecification node) { this.action(node); }
        public override void Visit(DatabaseAuditAction node) { this.action(node); }
        public override void Visit(AuditActionGroupReference node) { this.action(node); }
        public override void Visit(CreateDatabaseAuditSpecificationStatement node) { this.action(node); }
        public override void Visit(AlterDatabaseAuditSpecificationStatement node) { this.action(node); }
        public override void Visit(DropDatabaseAuditSpecificationStatement node) { this.action(node); }
        public override void Visit(CreateServerAuditSpecificationStatement node) { this.action(node); }
        public override void Visit(AlterServerAuditSpecificationStatement node) { this.action(node); }
        public override void Visit(DropServerAuditSpecificationStatement node) { this.action(node); }
        public override void Visit(CreateServerAuditStatement node) { this.action(node); }
        public override void Visit(AlterServerAuditStatement node) { this.action(node); }
        public override void Visit(DropServerAuditStatement node) { this.action(node); }
        public override void Visit(AuditTarget node) { this.action(node); }
        public override void Visit(QueueDelayAuditOption node) { this.action(node); }
        public override void Visit(AuditGuidAuditOption node) { this.action(node); }
        public override void Visit(OnFailureAuditOption node) { this.action(node); }
        public override void Visit(StateAuditOption node) { this.action(node); }
        public override void Visit(MaxSizeAuditTargetOption node) { this.action(node); }
        public override void Visit(MaxRolloverFilesAuditTargetOption node) { this.action(node); }
        public override void Visit(LiteralAuditTargetOption node) { this.action(node); }
        public override void Visit(OnOffAuditTargetOption node) { this.action(node); }
        public override void Visit(CreateDatabaseEncryptionKeyStatement node) { this.action(node); }
        public override void Visit(AlterDatabaseEncryptionKeyStatement node) { this.action(node); }
        public override void Visit(DropDatabaseEncryptionKeyStatement node) { this.action(node); }
        public override void Visit(ResourcePoolStatement node) { this.action(node); }
        public override void Visit(ResourcePoolParameter node) { this.action(node); }
        public override void Visit(ResourcePoolAffinitySpecification node) { this.action(node); }
        public override void Visit(CreateResourcePoolStatement node) { this.action(node); }
        public override void Visit(AlterResourcePoolStatement node) { this.action(node); }
        public override void Visit(DropResourcePoolStatement node) { this.action(node); }
        public override void Visit(WorkloadGroupResourceParameter node) { this.action(node); }
        public override void Visit(WorkloadGroupImportanceParameter node) { this.action(node); }
        public override void Visit(CreateWorkloadGroupStatement node) { this.action(node); }
        public override void Visit(AlterWorkloadGroupStatement node) { this.action(node); }
        public override void Visit(DropWorkloadGroupStatement node) { this.action(node); }
        public override void Visit(BrokerPriorityParameter node) { this.action(node); }
        public override void Visit(CreateBrokerPriorityStatement node) { this.action(node); }
        public override void Visit(AlterBrokerPriorityStatement node) { this.action(node); }
        public override void Visit(DropBrokerPriorityStatement node) { this.action(node); }
        public override void Visit(CreateFullTextStopListStatement node) { this.action(node); }
        public override void Visit(AlterFullTextStopListStatement node) { this.action(node); }
        public override void Visit(FullTextStopListAction node) { this.action(node); }
        public override void Visit(DropFullTextStopListStatement node) { this.action(node); }
        public override void Visit(CreateCryptographicProviderStatement node) { this.action(node); }
        public override void Visit(AlterCryptographicProviderStatement node) { this.action(node); }
        public override void Visit(DropCryptographicProviderStatement node) { this.action(node); }
        public override void Visit(EventSessionObjectName node) { this.action(node); }
        public override void Visit(EventSessionStatement node) { this.action(node); }
        public override void Visit(DropSearchPropertyListStatement node) { this.action(node); }
        public override void Visit(CreateLoginStatement node) { this.action(node); }
        public override void Visit(PasswordCreateLoginSource node) { this.action(node); }
        public override void Visit(PrincipalOption node) { this.action(node); }
        public override void Visit(OnOffPrincipalOption node) { this.action(node); }
        public override void Visit(LiteralPrincipalOption node) { this.action(node); }
        public override void Visit(IdentifierPrincipalOption node) { this.action(node); }
        public override void Visit(WindowsCreateLoginSource node) { this.action(node); }
        public override void Visit(CertificateCreateLoginSource node) { this.action(node); }
        public override void Visit(AsymmetricKeyCreateLoginSource node) { this.action(node); }
        public override void Visit(PasswordAlterPrincipalOption node) { this.action(node); }
        public override void Visit(AlterLoginOptionsStatement node) { this.action(node); }
        public override void Visit(AlterLoginEnableDisableStatement node) { this.action(node); }
        public override void Visit(AlterLoginAddDropCredentialStatement node) { this.action(node); }
        public override void Visit(RevertStatement node) { this.action(node); }
        public override void Visit(DropContractStatement node) { this.action(node); }
        public override void Visit(DropEndpointStatement node) { this.action(node); }
        public override void Visit(DropMessageTypeStatement node) { this.action(node); }
        public override void Visit(DropQueueStatement node) { this.action(node); }
        public override void Visit(DropRemoteServiceBindingStatement node) { this.action(node); }
        public override void Visit(DropRouteStatement node) { this.action(node); }
        public override void Visit(DropServiceStatement node) { this.action(node); }
        public override void Visit(AddSignatureStatement node) { this.action(node); }
        public override void Visit(DropSignatureStatement node) { this.action(node); }
        public override void Visit(DropEventNotificationStatement node) { this.action(node); }
        public override void Visit(ExecuteAsStatement node) { this.action(node); }
        public override void Visit(EndConversationStatement node) { this.action(node); }
        public override void Visit(MoveConversationStatement node) { this.action(node); }
        public override void Visit(GetConversationGroupStatement node) { this.action(node); }
        public override void Visit(ReceiveStatement node) { this.action(node); }
        public override void Visit(SendStatement node) { this.action(node); }
        public override void Visit(AlterSchemaStatement node) { this.action(node); }
        public override void Visit(AlterAsymmetricKeyStatement node) { this.action(node); }
        public override void Visit(AlterServiceMasterKeyStatement node) { this.action(node); }
        public override void Visit(BeginConversationTimerStatement node) { this.action(node); }
        public override void Visit(BeginDialogStatement node) { this.action(node); }
        public override void Visit(ScalarExpressionDialogOption node) { this.action(node); }
        public override void Visit(OnOffDialogOption node) { this.action(node); }
        public override void Visit(BackupCertificateStatement node) { this.action(node); }
        public override void Visit(BackupServiceMasterKeyStatement node) { this.action(node); }
        public override void Visit(RestoreServiceMasterKeyStatement node) { this.action(node); }
        public override void Visit(BackupMasterKeyStatement node) { this.action(node); }
        public override void Visit(RestoreMasterKeyStatement node) { this.action(node); }
        public override void Visit(ScalarExpressionSnippet node) { this.action(node); }
        public override void Visit(BooleanExpressionSnippet node) { this.action(node); }
        public override void Visit(StatementListSnippet node) { this.action(node); }
        public override void Visit(SelectStatementSnippet node) { this.action(node); }
        public override void Visit(SchemaObjectNameSnippet node) { this.action(node); }
        public override void Visit(TSqlFragmentSnippet node) { this.action(node); }
        public override void Visit(TSqlStatementSnippet node) { this.action(node); }
        public override void Visit(IdentifierSnippet node) { this.action(node); }
        public override void Visit(TSqlScript node) { this.action(node); }
        public override void Visit(TSqlBatch node) { this.action(node); }
        public override void Visit(MergeStatement node) { this.action(node); }
        public override void Visit(MergeSpecification node) { this.action(node); }
        public override void Visit(GrandTotalGroupingSpecification node) { this.action(node); }
        public override void Visit(GroupingSetsGroupingSpecification node) { this.action(node); }
        public override void Visit(OutputClause node) { this.action(node); }
        public override void Visit(OutputIntoClause node) { this.action(node); }
        public override void Visit(HavingClause node) { this.action(node); }
        public override void Visit(IdentityFunctionCall node) { this.action(node); }
        public override void Visit(JoinParenthesisTableReference node) { this.action(node); }
        public override void Visit(OrderByClause node) { this.action(node); }
        public override void Visit(QualifiedJoin node) { this.action(node); }
        public override void Visit(OdbcQualifiedJoinTableReference node) { this.action(node); }
        public override void Visit(QueryParenthesisExpression node) { this.action(node); }
        public override void Visit(QuerySpecification node) { this.action(node); }
        public override void Visit(FromClause node) { this.action(node); }
        public override void Visit(SelectScalarExpression node) { this.action(node); }
        public override void Visit(SelectStarExpression node) { this.action(node); }
        public override void Visit(SelectSetVariable node) { this.action(node); }
        public override void Visit(DataModificationTableReference node) { this.action(node); }
        public override void Visit(ChangeTableChangesTableReference node) { this.action(node); }
        public override void Visit(ChangeTableVersionTableReference node) { this.action(node); }
        public override void Visit(BooleanTernaryExpression node) { this.action(node); }
        public override void Visit(TopRowFilter node) { this.action(node); }
        public override void Visit(OffsetClause node) { this.action(node); }
        public override void Visit(UnaryExpression node) { this.action(node); }
        public override void Visit(BinaryQueryExpression node) { this.action(node); }
        public override void Visit(VariableTableReference node) { this.action(node); }
        public override void Visit(VariableMethodCallTableReference node) { this.action(node); }
        public override void Visit(DropPartitionFunctionStatement node) { this.action(node); }
        public override void Visit(DropPartitionSchemeStatement node) { this.action(node); }
        public override void Visit(DropSynonymStatement node) { this.action(node); }
        public override void Visit(DropAggregateStatement node) { this.action(node); }
        public override void Visit(DropAssemblyStatement node) { this.action(node); }
        public override void Visit(DropApplicationRoleStatement node) { this.action(node); }
        public override void Visit(DropFullTextCatalogStatement node) { this.action(node); }
        public override void Visit(DropFullTextIndexStatement node) { this.action(node); }
        public override void Visit(DropLoginStatement node) { this.action(node); }
        public override void Visit(DropRoleStatement node) { this.action(node); }
        public override void Visit(DropTypeStatement node) { this.action(node); }
        public override void Visit(DropUserStatement node) { this.action(node); }
        public override void Visit(DropMasterKeyStatement node) { this.action(node); }
        public override void Visit(DropSymmetricKeyStatement node) { this.action(node); }
        public override void Visit(DropAsymmetricKeyStatement node) { this.action(node); }
        public override void Visit(DropCertificateStatement node) { this.action(node); }
        public override void Visit(DropCredentialStatement node) { this.action(node); }
        public override void Visit(AlterPartitionFunctionStatement node) { this.action(node); }
        public override void Visit(AlterPartitionSchemeStatement node) { this.action(node); }
        public override void Visit(AlterFullTextIndexStatement node) { this.action(node); }
        public override void Visit(SimpleAlterFullTextIndexAction node) { this.action(node); }
        public override void Visit(SetStopListAlterFullTextIndexAction node) { this.action(node); }
        public override void Visit(SetSearchPropertyListAlterFullTextIndexAction node) { this.action(node); }
        public override void Visit(DropAlterFullTextIndexAction node) { this.action(node); }
        public override void Visit(AddAlterFullTextIndexAction node) { this.action(node); }
        public override void Visit(AlterColumnAlterFullTextIndexAction node) { this.action(node); }
        public override void Visit(CreateSearchPropertyListStatement node) { this.action(node); }
        public override void Visit(AlterSearchPropertyListStatement node) { this.action(node); }
        public override void Visit(AddSearchPropertyListAction node) { this.action(node); }
        public override void Visit(DropSearchPropertyListAction node) { this.action(node); }
        public override void Visit(CreateAggregateStatement node) { this.action(node); }
        public override void Visit(CreateEndpointStatement node) { this.action(node); }
        public override void Visit(AlterEndpointStatement node) { this.action(node); }
        public override void Visit(EndpointAffinity node) { this.action(node); }
        public override void Visit(LiteralEndpointProtocolOption node) { this.action(node); }
        public override void Visit(AuthenticationEndpointProtocolOption node) { this.action(node); }
        public override void Visit(PortsEndpointProtocolOption node) { this.action(node); }
        public override void Visit(CompressionEndpointProtocolOption node) { this.action(node); }
        public override void Visit(ListenerIPEndpointProtocolOption node) { this.action(node); }
        public override void Visit(IPv4 node) { this.action(node); }
        public override void Visit(SoapMethod node) { this.action(node); }
        public override void Visit(EnabledDisabledPayloadOption node) { this.action(node); }
        public override void Visit(WsdlPayloadOption node) { this.action(node); }
        public override void Visit(LoginTypePayloadOption node) { this.action(node); }
        public override void Visit(LiteralPayloadOption node) { this.action(node); }
        public override void Visit(SessionTimeoutPayloadOption node) { this.action(node); }
        public override void Visit(SchemaPayloadOption node) { this.action(node); }
        public override void Visit(CharacterSetPayloadOption node) { this.action(node); }
        public override void Visit(RolePayloadOption node) { this.action(node); }
        public override void Visit(AuthenticationPayloadOption node) { this.action(node); }
        public override void Visit(EncryptionPayloadOption node) { this.action(node); }
        public override void Visit(CreateSymmetricKeyStatement node) { this.action(node); }
        public override void Visit(KeySourceKeyOption node) { this.action(node); }
        public override void Visit(AlgorithmKeyOption node) { this.action(node); }
        public override void Visit(IdentityValueKeyOption node) { this.action(node); }
        public override void Visit(ProviderKeyNameKeyOption node) { this.action(node); }
        public override void Visit(CreationDispositionKeyOption node) { this.action(node); }
        public override void Visit(AlterSymmetricKeyStatement node) { this.action(node); }
        public override void Visit(OnOffFullTextCatalogOption node) { this.action(node); }
        public override void Visit(CreateFullTextCatalogStatement node) { this.action(node); }
        public override void Visit(AlterFullTextCatalogStatement node) { this.action(node); }
        public override void Visit(CreateServiceStatement node) { this.action(node); }
        public override void Visit(AlterServiceStatement node) { this.action(node); }
        public override void Visit(ServiceContract node) { this.action(node); }
        public override void Visit(BinaryExpression node) { this.action(node); }
        public override void Visit(BuiltInFunctionTableReference node) { this.action(node); }
        public override void Visit(ComputeClause node) { this.action(node); }
        public override void Visit(ComputeFunction node) { this.action(node); }
        public override void Visit(PivotedTableReference node) { this.action(node); }
        public override void Visit(UnpivotedTableReference node) { this.action(node); }
        public override void Visit(UnqualifiedJoin node) { this.action(node); }
        public override void Visit(TableSampleClause node) { this.action(node); }
        public override void Visit(BooleanNotExpression node) { this.action(node); }
        public override void Visit(BooleanParenthesisExpression node) { this.action(node); }
        public override void Visit(BooleanComparisonExpression node) { this.action(node); }
        public override void Visit(BooleanBinaryExpression node) { this.action(node); }
        public override void Visit(BooleanIsNullExpression node) { this.action(node); }
        public override void Visit(ExpressionWithSortOrder node) { this.action(node); }
        public override void Visit(GroupByClause node) { this.action(node); }
        public override void Visit(ExpressionGroupingSpecification node) { this.action(node); }
        public override void Visit(CompositeGroupingSpecification node) { this.action(node); }
        public override void Visit(CubeGroupingSpecification node) { this.action(node); }
        public override void Visit(RollupGroupingSpecification node) { this.action(node); }
        public override void Visit(IdentityOptions node) { this.action(node); }
        public override void Visit(ColumnStorageOptions node) { this.action(node); }
        public override void Visit(CreateTableStatement node) { this.action(node); }
        public override void Visit(FederationScheme node) { this.action(node); }
        public override void Visit(TableDataCompressionOption node) { this.action(node); }
        public override void Visit(DataCompressionOption node) { this.action(node); }
        public override void Visit(CompressionPartitionRange node) { this.action(node); }
        public override void Visit(CheckConstraintDefinition node) { this.action(node); }
        public override void Visit(DefaultConstraintDefinition node) { this.action(node); }
        public override void Visit(ForeignKeyConstraintDefinition node) { this.action(node); }
        public override void Visit(NullableConstraintDefinition node) { this.action(node); }
        public override void Visit(UniqueConstraintDefinition node) { this.action(node); }
        public override void Visit(BackupDatabaseStatement node) { this.action(node); }
        public override void Visit(BackupTransactionLogStatement node) { this.action(node); }
        public override void Visit(RestoreStatement node) { this.action(node); }
        public override void Visit(RestoreOption node) { this.action(node); }
        public override void Visit(ScalarExpressionRestoreOption node) { this.action(node); }
        public override void Visit(MoveRestoreOption node) { this.action(node); }
        public override void Visit(StopRestoreOption node) { this.action(node); }
        public override void Visit(FileStreamRestoreOption node) { this.action(node); }
        public override void Visit(BackupOption node) { this.action(node); }
        public override void Visit(BackupEncryptionOption node) { this.action(node); }
        public override void Visit(DeviceInfo node) { this.action(node); }
        public override void Visit(MirrorToClause node) { this.action(node); }
        public override void Visit(BackupRestoreFileInfo node) { this.action(node); }
        public override void Visit(BulkInsertStatement node) { this.action(node); }
        public override void Visit(InsertBulkStatement node) { this.action(node); }
        public override void Visit(BulkInsertOption node) { this.action(node); }
        public override void Visit(LiteralBulkInsertOption node) { this.action(node); }
        public override void Visit(OrderBulkInsertOption node) { this.action(node); }
        public override void Visit(ColumnDefinitionBase node) { this.action(node); }
        public override void Visit(InsertBulkColumnDefinition node) { this.action(node); }
        public override void Visit(DbccStatement node) { this.action(node); }
        public override void Visit(DbccOption node) { this.action(node); }
        public override void Visit(DbccNamedLiteral node) { this.action(node); }
        public override void Visit(CreateAsymmetricKeyStatement node) { this.action(node); }
        public override void Visit(CreatePartitionFunctionStatement node) { this.action(node); }
        public override void Visit(PartitionParameterType node) { this.action(node); }
        public override void Visit(CreatePartitionSchemeStatement node) { this.action(node); }
        public override void Visit(OnOffRemoteServiceBindingOption node) { this.action(node); }
        public override void Visit(UserRemoteServiceBindingOption node) { this.action(node); }
        public override void Visit(CreateRemoteServiceBindingStatement node) { this.action(node); }
        public override void Visit(AlterRemoteServiceBindingStatement node) { this.action(node); }
        public override void Visit(AssemblyEncryptionSource node) { this.action(node); }
        public override void Visit(FileEncryptionSource node) { this.action(node); }
        public override void Visit(ProviderEncryptionSource node) { this.action(node); }
        public override void Visit(AlterCertificateStatement node) { this.action(node); }
        public override void Visit(CreateCertificateStatement node) { this.action(node); }
        public override void Visit(CertificateOption node) { this.action(node); }
        public override void Visit(CreateContractStatement node) { this.action(node); }
        public override void Visit(ContractMessage node) { this.action(node); }
        public override void Visit(CreateCredentialStatement node) { this.action(node); }
        public override void Visit(AlterCredentialStatement node) { this.action(node); }
        public override void Visit(CreateMessageTypeStatement node) { this.action(node); }
        public override void Visit(AlterMessageTypeStatement node) { this.action(node); }
        public override void Visit(KillStatsJobStatement node) { this.action(node); }
        public override void Visit(CheckpointStatement node) { this.action(node); }
        public override void Visit(ReconfigureStatement node) { this.action(node); }
        public override void Visit(ShutdownStatement node) { this.action(node); }
        public override void Visit(SetUserStatement node) { this.action(node); }
        public override void Visit(TruncateTableStatement node) { this.action(node); }
        public override void Visit(PredicateSetStatement node) { this.action(node); }
        public override void Visit(SetStatisticsStatement node) { this.action(node); }
        public override void Visit(SetRowCountStatement node) { this.action(node); }
        public override void Visit(SetOffsetsStatement node) { this.action(node); }
        public override void Visit(GeneralSetCommand node) { this.action(node); }
        public override void Visit(SetFipsFlaggerCommand node) { this.action(node); }
        public override void Visit(SetCommandStatement node) { this.action(node); }
        public override void Visit(SetTransactionIsolationLevelStatement node) { this.action(node); }
        public override void Visit(SetTextSizeStatement node) { this.action(node); }
        public override void Visit(SetIdentityInsertStatement node) { this.action(node); }
        public override void Visit(SetErrorLevelStatement node) { this.action(node); }
        public override void Visit(CreateDatabaseStatement node) { this.action(node); }
        public override void Visit(FileDeclaration node) { this.action(node); }
        public override void Visit(FileDeclarationOption node) { this.action(node); }
        public override void Visit(NameFileDeclarationOption node) { this.action(node); }
        public override void Visit(FileNameFileDeclarationOption node) { this.action(node); }
        public override void Visit(SizeFileDeclarationOption node) { this.action(node); }
        public override void Visit(MaxSizeFileDeclarationOption node) { this.action(node); }
        public override void Visit(FileGrowthFileDeclarationOption node) { this.action(node); }
        public override void Visit(FileGroupDefinition node) { this.action(node); }
        public override void Visit(AlterDatabaseCollateStatement node) { this.action(node); }
        public override void Visit(AlterDatabaseRebuildLogStatement node) { this.action(node); }
        public override void Visit(AlterDatabaseAddFileStatement node) { this.action(node); }
        public override void Visit(AlterDatabaseAddFileGroupStatement node) { this.action(node); }
        public override void Visit(AlterDatabaseRemoveFileGroupStatement node) { this.action(node); }
        public override void Visit(AlterDatabaseRemoveFileStatement node) { this.action(node); }
        public override void Visit(AlterDatabaseModifyNameStatement node) { this.action(node); }
        public override void Visit(AlterDatabaseModifyFileStatement node) { this.action(node); }
        public override void Visit(AlterDatabaseModifyFileGroupStatement node) { this.action(node); }
        public override void Visit(AlterDatabaseTermination node) { this.action(node); }
        public override void Visit(AlterDatabaseSetStatement node) { this.action(node); }
        public override void Visit(DatabaseOption node) { this.action(node); }
        public override void Visit(OnOffDatabaseOption node) { this.action(node); }
        public override void Visit(AutoCreateStatisticsDatabaseOption node) { this.action(node); }
        public override void Visit(ContainmentDatabaseOption node) { this.action(node); }
        public override void Visit(HadrDatabaseOption node) { this.action(node); }
        public override void Visit(HadrAvailabilityGroupDatabaseOption node) { this.action(node); }
        public override void Visit(DelayedDurabilityDatabaseOption node) { this.action(node); }
        public override void Visit(CursorDefaultDatabaseOption node) { this.action(node); }
        public override void Visit(RecoveryDatabaseOption node) { this.action(node); }
        public override void Visit(TargetRecoveryTimeDatabaseOption node) { this.action(node); }
        public override void Visit(PageVerifyDatabaseOption node) { this.action(node); }
        public override void Visit(PartnerDatabaseOption node) { this.action(node); }
        public override void Visit(WitnessDatabaseOption node) { this.action(node); }
        public override void Visit(ParameterizationDatabaseOption node) { this.action(node); }
        public override void Visit(LiteralDatabaseOption node) { this.action(node); }
        public override void Visit(IdentifierDatabaseOption node) { this.action(node); }
        public override void Visit(ChangeTrackingDatabaseOption node) { this.action(node); }
        public override void Visit(AutoCleanupChangeTrackingOptionDetail node) { this.action(node); }
        public override void Visit(ChangeRetentionChangeTrackingOptionDetail node) { this.action(node); }
        public override void Visit(FileStreamDatabaseOption node) { this.action(node); }
        public override void Visit(MaxSizeDatabaseOption node) { this.action(node); }
        public override void Visit(AlterTableAlterColumnStatement node) { this.action(node); }
        public override void Visit(ColumnDefinition node) { this.action(node); }
        public override void Visit(CreateRoleStatement node) { this.action(node); }
        public override void Visit(AlterRoleStatement node) { this.action(node); }
        public override void Visit(RenameAlterRoleAction node) { this.action(node); }
        public override void Visit(AddMemberAlterRoleAction node) { this.action(node); }
        public override void Visit(DropMemberAlterRoleAction node) { this.action(node); }
        public override void Visit(CreateServerRoleStatement node) { this.action(node); }
        public override void Visit(AlterServerRoleStatement node) { this.action(node); }
        public override void Visit(DropServerRoleStatement node) { this.action(node); }
        public override void Visit(UserLoginOption node) { this.action(node); }
        public override void Visit(CreateUserStatement node) { this.action(node); }
        public override void Visit(AlterUserStatement node) { this.action(node); }
        public override void Visit(StatisticsOption node) { this.action(node); }
        public override void Visit(ResampleStatisticsOption node) { this.action(node); }
        public override void Visit(StatisticsPartitionRange node) { this.action(node); }
        public override void Visit(OnOffStatisticsOption node) { this.action(node); }
        public override void Visit(LiteralStatisticsOption node) { this.action(node); }
        public override void Visit(CreateStatisticsStatement node) { this.action(node); }
        public override void Visit(UpdateStatisticsStatement node) { this.action(node); }
        public override void Visit(ReturnStatement node) { this.action(node); }
        public override void Visit(DeclareCursorStatement node) { this.action(node); }
        public override void Visit(CursorDefinition node) { this.action(node); }
        public override void Visit(CursorOption node) { this.action(node); }
        public override void Visit(SetVariableStatement node) { this.action(node); }
        public override void Visit(CursorId node) { this.action(node); }
        public override void Visit(OpenCursorStatement node) { this.action(node); }
        public override void Visit(CloseCursorStatement node) { this.action(node); }
        public override void Visit(CryptoMechanism node) { this.action(node); }
        public override void Visit(OpenSymmetricKeyStatement node) { this.action(node); }
        public override void Visit(CloseSymmetricKeyStatement node) { this.action(node); }
        public override void Visit(OpenMasterKeyStatement node) { this.action(node); }
        public override void Visit(CloseMasterKeyStatement node) { this.action(node); }
        public override void Visit(DeallocateCursorStatement node) { this.action(node); }
        public override void Visit(FetchType node) { this.action(node); }
        public override void Visit(FetchCursorStatement node) { this.action(node); }
        public override void Visit(WhereClause node) { this.action(node); }
        public override void Visit(DropDatabaseStatement node) { this.action(node); }
        public override void Visit(DropIndexStatement node) { this.action(node); }
        public override void Visit(BackwardsCompatibleDropIndexClause node) { this.action(node); }
        public override void Visit(DropIndexClause node) { this.action(node); }
        public override void Visit(MoveToDropIndexOption node) { this.action(node); }
        public override void Visit(FileStreamOnDropIndexOption node) { this.action(node); }
        public override void Visit(DropStatisticsStatement node) { this.action(node); }
        public override void Visit(DropTableStatement node) { this.action(node); }
        public override void Visit(DropProcedureStatement node) { this.action(node); }
        public override void Visit(DropFunctionStatement node) { this.action(node); }
        public override void Visit(DropViewStatement node) { this.action(node); }
        public override void Visit(DropDefaultStatement node) { this.action(node); }
        public override void Visit(DropRuleStatement node) { this.action(node); }
        public override void Visit(DropTriggerStatement node) { this.action(node); }
        public override void Visit(DropSchemaStatement node) { this.action(node); }
        public override void Visit(RaiseErrorLegacyStatement node) { this.action(node); }
        public override void Visit(RaiseErrorStatement node) { this.action(node); }
        public override void Visit(ThrowStatement node) { this.action(node); }
        public override void Visit(UseStatement node) { this.action(node); }
        public override void Visit(KillStatement node) { this.action(node); }
        public override void Visit(KillQueryNotificationSubscriptionStatement node) { this.action(node); }
        public override void Visit(LowPriorityLockWaitTableSwitchOption node) { this.action(node); }
        public override void Visit(DropClusteredConstraintStateOption node) { this.action(node); }
        public override void Visit(DropClusteredConstraintValueOption node) { this.action(node); }
        public override void Visit(DropClusteredConstraintMoveOption node) { this.action(node); }
        public override void Visit(AlterTableDropTableElement node) { this.action(node); }
        public override void Visit(AlterTableDropTableElementStatement node) { this.action(node); }
        public override void Visit(AlterTableTriggerModificationStatement node) { this.action(node); }
        public override void Visit(EnableDisableTriggerStatement node) { this.action(node); }
        public override void Visit(TryCatchStatement node) { this.action(node); }
        public override void Visit(CreateTypeUdtStatement node) { this.action(node); }
        public override void Visit(CreateTypeUddtStatement node) { this.action(node); }
        public override void Visit(CreateSynonymStatement node) { this.action(node); }
        public override void Visit(ExecuteAsClause node) { this.action(node); }
        public override void Visit(QueueOption node) { this.action(node); }
        public override void Visit(QueueStateOption node) { this.action(node); }
        public override void Visit(QueueProcedureOption node) { this.action(node); }
        public override void Visit(QueueValueOption node) { this.action(node); }
        public override void Visit(QueueExecuteAsOption node) { this.action(node); }
        public override void Visit(RouteOption node) { this.action(node); }
        public override void Visit(AlterRouteStatement node) { this.action(node); }
        public override void Visit(CreateRouteStatement node) { this.action(node); }
        public override void Visit(AlterQueueStatement node) { this.action(node); }
        public override void Visit(CreateQueueStatement node) { this.action(node); }
        public override void Visit(IndexDefinition node) { this.action(node); }
        public override void Visit(IndexType node) { this.action(node); }
        public override void Visit(PartitionSpecifier node) { this.action(node); }
        public override void Visit(AlterIndexStatement node) { this.action(node); }
        public override void Visit(CreateXmlIndexStatement node) { this.action(node); }
        public override void Visit(CreateSelectiveXmlIndexStatement node) { this.action(node); }
        public override void Visit(FileGroupOrPartitionScheme node) { this.action(node); }
        public override void Visit(CreateIndexStatement node) { this.action(node); }
        public override void Visit(IndexStateOption node) { this.action(node); }
        public override void Visit(IndexExpressionOption node) { this.action(node); }
        public override void Visit(OnlineIndexOption node) { this.action(node); }
        public override void Visit(OnlineIndexLowPriorityLockWaitOption node) { this.action(node); }
        public override void Visit(LowPriorityLockWaitMaxDurationOption node) { this.action(node); }
        public override void Visit(LowPriorityLockWaitAbortAfterWaitOption node) { this.action(node); }
        public override void Visit(FullTextIndexColumn node) { this.action(node); }
        public override void Visit(CreateFullTextIndexStatement node) { this.action(node); }
        public override void Visit(ChangeTrackingFullTextIndexOption node) { this.action(node); }
        public override void Visit(StopListFullTextIndexOption node) { this.action(node); }
        public override void Visit(SearchPropertyListFullTextIndexOption node) { this.action(node); }
        public override void Visit(FullTextCatalogAndFileGroup node) { this.action(node); }
        public override void Visit(EventTypeContainer node) { this.action(node); }
        public override void Visit(EventGroupContainer node) { this.action(node); }
        public override void Visit(CreateEventNotificationStatement node) { this.action(node); }
        public override void Visit(EventNotificationObjectScope node) { this.action(node); }
        public override void Visit(CreateMasterKeyStatement node) { this.action(node); }
        public override void Visit(AlterMasterKeyStatement node) { this.action(node); }
        public override void Visit(ApplicationRoleOption node) { this.action(node); }
        public override void Visit(CreateApplicationRoleStatement node) { this.action(node); }
        public override void Visit(AlterApplicationRoleStatement node) { this.action(node); }
        public override void Visit(ExecuteInsertSource node) { this.action(node); }
        public override void Visit(RowValue node) { this.action(node); }
        public override void Visit(PrintStatement node) { this.action(node); }
        public override void Visit(UpdateCall node) { this.action(node); }
        public override void Visit(TSEqualCall node) { this.action(node); }
        public override void Visit(IntegerLiteral node) { this.action(node); }
        public override void Visit(NumericLiteral node) { this.action(node); }
        public override void Visit(RealLiteral node) { this.action(node); }
        public override void Visit(MoneyLiteral node) { this.action(node); }
        public override void Visit(BinaryLiteral node) { this.action(node); }
        public override void Visit(StringLiteral node) { this.action(node); }
        public override void Visit(NullLiteral node) { this.action(node); }
        public override void Visit(IdentifierLiteral node) { this.action(node); }
        public override void Visit(DefaultLiteral node) { this.action(node); }
        public override void Visit(MaxLiteral node) { this.action(node); }
        public override void Visit(OdbcLiteral node) { this.action(node); }
        public override void Visit(LiteralRange node) { this.action(node); }
        public override void Visit(VariableReference node) { this.action(node); }
        public override void Visit(OnOffOptionValue node) { this.action(node); }
        public override void Visit(LiteralOptionValue node) { this.action(node); }
        public override void Visit(GlobalVariableExpression node) { this.action(node); }
        public override void Visit(IdentifierOrValueExpression node) { this.action(node); }
        public override void Visit(SchemaObjectNameOrValueExpression node) { this.action(node); }
        public override void Visit(ParenthesisExpression node) { this.action(node); }
        public override void Visit(ColumnReferenceExpression node) { this.action(node); }
        public override void Visit(NextValueForExpression node) { this.action(node); }
        public override void Visit(SequenceOption node) { this.action(node); }
        public override void Visit(DataTypeSequenceOption node) { this.action(node); }
        public override void Visit(ScalarExpressionSequenceOption node) { this.action(node); }
        public override void Visit(CreateSequenceStatement node) { this.action(node); }
        public override void Visit(AlterSequenceStatement node) { this.action(node); }
        public override void Visit(DropSequenceStatement node) { this.action(node); }
        public override void Visit(CreateAssemblyStatement node) { this.action(node); }
        public override void Visit(AlterAssemblyStatement node) { this.action(node); }
        public override void Visit(AssemblyOption node) { this.action(node); }
        public override void Visit(OnOffAssemblyOption node) { this.action(node); }
        public override void Visit(PermissionSetAssemblyOption node) { this.action(node); }
        public override void Visit(AddFileSpec node) { this.action(node); }
        public override void Visit(CreateXmlSchemaCollectionStatement node) { this.action(node); }
        public override void Visit(AlterXmlSchemaCollectionStatement node) { this.action(node); }
        public override void Visit(DropXmlSchemaCollectionStatement node) { this.action(node); }
        public override void Visit(AssemblyName node) { this.action(node); }
        public override void Visit(AlterTableRebuildStatement node) { this.action(node); }
        public override void Visit(AlterTableChangeTrackingModificationStatement node) { this.action(node); }
        public override void Visit(AlterTableFileTableNamespaceStatement node) { this.action(node); }
        public override void Visit(AlterTableSetStatement node) { this.action(node); }
        public override void Visit(LockEscalationTableOption node) { this.action(node); }
        public override void Visit(FileStreamOnTableOption node) { this.action(node); }
        public override void Visit(FileTableDirectoryTableOption node) { this.action(node); }
        public override void Visit(FileTableCollateFileNameTableOption node) { this.action(node); }
        public override void Visit(FileTableConstraintNameTableOption node) { this.action(node); }
        public override void Visit(MemoryOptimizedTableOption node) { this.action(node); }
        public override void Visit(DurabilityTableOption node) { this.action(node); }
        public override void Visit(AlterTableAddTableElementStatement node) { this.action(node); }
        public override void Visit(AlterTableConstraintModificationStatement node) { this.action(node); }
        public override void Visit(AlterTableSwitchStatement node) { this.action(node); }
        public override void Visit(LiteralAtomicBlockOption node) { this.action(node); }
        public override void Visit(IdentifierAtomicBlockOption node) { this.action(node); }
        public override void Visit(OnOffAtomicBlockOption node) { this.action(node); }
        public override void Visit(BeginTransactionStatement node) { this.action(node); }
        public override void Visit(BreakStatement node) { this.action(node); }
        public override void Visit(ColumnWithSortOrder node) { this.action(node); }
        public override void Visit(CommitTransactionStatement node) { this.action(node); }
        public override void Visit(RollbackTransactionStatement node) { this.action(node); }
        public override void Visit(SaveTransactionStatement node) { this.action(node); }
        public override void Visit(ContinueStatement node) { this.action(node); }
        public override void Visit(CreateDefaultStatement node) { this.action(node); }
        public override void Visit(CreateFunctionStatement node) { this.action(node); }
        public override void Visit(CreateRuleStatement node) { this.action(node); }
        public override void Visit(DeclareVariableElement node) { this.action(node); }
        public override void Visit(DeclareVariableStatement node) { this.action(node); }
        public override void Visit(GoToStatement node) { this.action(node); }
        public override void Visit(IfStatement node) { this.action(node); }
        public override void Visit(LabelStatement node) { this.action(node); }
        public override void Visit(MultiPartIdentifier node) { this.action(node); }
        public override void Visit(SchemaObjectName node) { this.action(node); }
        public override void Visit(ChildObjectName node) { this.action(node); }
        public override void Visit(ProcedureParameter node) { this.action(node); }
        public override void Visit(WhileStatement node) { this.action(node); }
        public override void Visit(DeleteStatement node) { this.action(node); }
        public override void Visit(DeleteSpecification node) { this.action(node); }
        public override void Visit(InsertStatement node) { this.action(node); }
        public override void Visit(InsertSpecification node) { this.action(node); }
        public override void Visit(UpdateStatement node) { this.action(node); }
        public override void Visit(UpdateSpecification node) { this.action(node); }
        public override void Visit(CreateSchemaStatement node) { this.action(node); }
        public override void Visit(WaitForStatement node) { this.action(node); }
        public override void Visit(ReadTextStatement node) { this.action(node); }
        public override void Visit(UpdateTextStatement node) { this.action(node); }
        public override void Visit(WriteTextStatement node) { this.action(node); }
        public override void Visit(LineNoStatement node) { this.action(node); }
        public override void Visit(GrantStatement node) { this.action(node); }
        public override void Visit(DenyStatement node) { this.action(node); }
        public override void Visit(RevokeStatement node) { this.action(node); }
        public override void Visit(AlterAuthorizationStatement node) { this.action(node); }
        public override void Visit(Permission node) { this.action(node); }
        public override void Visit(SecurityTargetObject node) { this.action(node); }
        public override void Visit(SecurityTargetObjectName node) { this.action(node); }
        public override void Visit(SecurityPrincipal node) { this.action(node); }
        public override void Visit(GrantStatement80 node) { this.action(node); }
        public override void Visit(DenyStatement80 node) { this.action(node); }
        public override void Visit(RevokeStatement80 node) { this.action(node); }
        public override void Visit(CommandSecurityElement80 node) { this.action(node); }
        public override void Visit(PrivilegeSecurityElement80 node) { this.action(node); }
        public override void Visit(Privilege80 node) { this.action(node); }
        public override void Visit(SecurityUserClause80 node) { this.action(node); }
        public override void Visit(SqlCommandIdentifier node) { this.action(node); }
        public override void Visit(AssignmentSetClause node) { this.action(node); }
        public override void Visit(FunctionCallSetClause node) { this.action(node); }
        public override void Visit(ValuesInsertSource node) { this.action(node); }
        public override void Visit(SelectInsertSource node) { this.action(node); }
        public override void Visit(LiteralTableHint node) { this.action(node); }
        public override void Visit(QueryDerivedTable node) { this.action(node); }
        public override void Visit(InlineDerivedTable node) { this.action(node); }
        public override void Visit(SubqueryComparisonPredicate node) { this.action(node); }
        public override void Visit(ExistsPredicate node) { this.action(node); }
        public override void Visit(LikePredicate node) { this.action(node); }
        public override void Visit(InPredicate node) { this.action(node); }
        public override void Visit(FullTextPredicate node) { this.action(node); }
        public override void Visit(UserDefinedTypePropertyAccess node) { this.action(node); }
        public override void Visit(SelectStatement node) { this.action(node); }
        public override void Visit(BrowseForClause node) { this.action(node); }
        public override void Visit(ReadOnlyForClause node) { this.action(node); }
        public override void Visit(XmlForClause node) { this.action(node); }
        public override void Visit(XmlForClauseOption node) { this.action(node); }
        public override void Visit(UpdateForClause node) { this.action(node); }
        public override void Visit(OptimizerHint node) { this.action(node); }
        public override void Visit(LiteralOptimizerHint node) { this.action(node); }
        public override void Visit(TableHintsOptimizerHint node) { this.action(node); }
        public override void Visit(ForceSeekTableHint node) { this.action(node); }
        public override void Visit(OptimizeForOptimizerHint node) { this.action(node); }
        public override void Visit(VariableValuePair node) { this.action(node); }
        public override void Visit(SimpleWhenClause node) { this.action(node); }
        public override void Visit(SearchedWhenClause node) { this.action(node); }
        public override void Visit(SimpleCaseExpression node) { this.action(node); }
        public override void Visit(SearchedCaseExpression node) { this.action(node); }
        public override void Visit(NullIfExpression node) { this.action(node); }
        public override void Visit(CoalesceExpression node) { this.action(node); }
        public override void Visit(IIfCall node) { this.action(node); }
        public override void Visit(FullTextTableReference node) { this.action(node); }
        public override void Visit(SemanticTableReference node) { this.action(node); }
        public override void Visit(OpenXmlTableReference node) { this.action(node); }
        public override void Visit(OpenRowsetTableReference node) { this.action(node); }
        public override void Visit(InternalOpenRowset node) { this.action(node); }
        public override void Visit(BulkOpenRowset node) { this.action(node); }
        public override void Visit(OpenQueryTableReference node) { this.action(node); }
        public override void Visit(AdHocTableReference node) { this.action(node); }
        public override void Visit(SchemaDeclarationItem node) { this.action(node); }
        public override void Visit(ConvertCall node) { this.action(node); }
        public override void Visit(TryConvertCall node) { this.action(node); }
        public override void Visit(ParseCall node) { this.action(node); }
        public override void Visit(TryParseCall node) { this.action(node); }
        public override void Visit(CastCall node) { this.action(node); }
        public override void Visit(TryCastCall node) { this.action(node); }
        public override void Visit(FunctionCall node) { this.action(node); }
        public override void Visit(ExpressionCallTarget node) { this.action(node); }
        public override void Visit(MultiPartIdentifierCallTarget node) { this.action(node); }
        public override void Visit(UserDefinedTypeCallTarget node) { this.action(node); }
        public override void Visit(LeftFunctionCall node) { this.action(node); }
        public override void Visit(RightFunctionCall node) { this.action(node); }
        public override void Visit(PartitionFunctionCall node) { this.action(node); }
        public override void Visit(OverClause node) { this.action(node); }
        public override void Visit(ParameterlessCall node) { this.action(node); }
        public override void Visit(ScalarSubquery node) { this.action(node); }
        public override void Visit(OdbcFunctionCall node) { this.action(node); }
        public override void Visit(ExtractFromExpression node) { this.action(node); }
        public override void Visit(OdbcConvertSpecification node) { this.action(node); }
        public override void Visit(AlterFunctionStatement node) { this.action(node); }
        public override void Visit(BeginEndBlockStatement node) { this.action(node); }
        public override void Visit(BeginEndAtomicBlockStatement node) { this.action(node); }
        public override void Visit(StatementList node) { this.action(node); }
        public override void Visit(ExecuteStatement node) { this.action(node); }
        public override void Visit(ExecuteOption node) { this.action(node); }
        public override void Visit(ResultSetsExecuteOption node) { this.action(node); }
        public override void Visit(ResultSetDefinition node) { this.action(node); }
        public override void Visit(InlineResultSetDefinition node) { this.action(node); }
        public override void Visit(ResultColumnDefinition node) { this.action(node); }
        public override void Visit(SchemaObjectResultSetDefinition node) { this.action(node); }
        public override void Visit(ExecuteSpecification node) { this.action(node); }
        public override void Visit(ExecuteContext node) { this.action(node); }
        public override void Visit(ExecuteParameter node) { this.action(node); }
        public override void Visit(ProcedureReferenceName node) { this.action(node); }
        public override void Visit(ExecutableProcedureReference node) { this.action(node); }
        public override void Visit(ExecutableStringList node) { this.action(node); }
        public override void Visit(AdHocDataSource node) { this.action(node); }
        public override void Visit(ViewOption node) { this.action(node); }
        public override void Visit(AlterViewStatement node) { this.action(node); }
        public override void Visit(CreateViewStatement node) { this.action(node); }
        public override void Visit(TriggerObject node) { this.action(node); }
        public override void Visit(TriggerOption node) { this.action(node); }
        public override void Visit(ExecuteAsTriggerOption node) { this.action(node); }
        public override void Visit(TriggerAction node) { this.action(node); }
        public override void Visit(AlterTriggerStatement node) { this.action(node); }
        public override void Visit(CreateTriggerStatement node) { this.action(node); }
        public override void Visit(Identifier node) { this.action(node); }
        public override void Visit(AlterProcedureStatement node) { this.action(node); }
        public override void Visit(CreateProcedureStatement node) { this.action(node); }
        public override void Visit(ProcedureReference node) { this.action(node); }
        public override void Visit(MethodSpecifier node) { this.action(node); }
        public override void Visit(ProcedureOption node) { this.action(node); }
        public override void Visit(ExecuteAsProcedureOption node) { this.action(node); }
        public override void Visit(FunctionOption node) { this.action(node); }
        public override void Visit(ExecuteAsFunctionOption node) { this.action(node); }
        public override void Visit(XmlNamespaces node) { this.action(node); }
        public override void Visit(XmlNamespacesDefaultElement node) { this.action(node); }
        public override void Visit(XmlNamespacesAliasElement node) { this.action(node); }
        public override void Visit(CommonTableExpression node) { this.action(node); }
        public override void Visit(WithCtesAndXmlNamespaces node) { this.action(node); }
        public override void Visit(TableValuedFunctionReturnType node) { this.action(node); }
        public override void Visit(SqlDataTypeReference node) { this.action(node); }
        public override void Visit(UserDataTypeReference node) { this.action(node); }
        public override void Visit(XmlDataTypeReference node) { this.action(node); }
        public override void Visit(ScalarFunctionReturnType node) { this.action(node); }
        public override void Visit(SelectFunctionReturnType node) { this.action(node); }
        public override void Visit(TableDefinition node) { this.action(node); }
        public override void Visit(DeclareTableVariableBody node) { this.action(node); }
        public override void Visit(DeclareTableVariableStatement node) { this.action(node); }
        public override void Visit(NamedTableReference node) { this.action(node); }
        public override void Visit(SchemaObjectFunctionTableReference node) { this.action(node); }
        public override void Visit(TableHint node) { this.action(node); }
        public override void Visit(IndexTableHint node) { this.action(node); }

    }
}